# Docker Compose para CoreApp - Sistema SAAS Multi-tenant Brasileiro
# Configuração para desenvolvimento e produção com Traefik
version: '3.8'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: coreapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: coreapp_saas_prod
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev123456}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=pt_BR.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - coreapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d coreapp_saas_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CoreApp Application
  coreapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coreapp_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=coreapp_saas_prod;User Id=admin;Password=${DB_PASSWORD:-dev123456};
      
      # Security
      - JWT__Secret=${JWT_SECRET:-sua-chave-secreta-muito-segura-aqui-com-pelo-menos-32-caracteres}
      - JWT__Issuer=CoreAPIBrasil
      - JWT__Audience=CoreAppClientsBrasil
      
      # Multi-tenant
      - MultiTenant__DefaultTenant=demo
      - MultiTenant__TenantDomain=${DOMAIN:-coreapp-dev.diegolima.dev}
      - MultiTenant__AdminDomain=admin.${DOMAIN:-coreapp-dev.diegolima.dev}
      
      # Rate Limiting
      - RateLimit__MaxRequests=100
      - RateLimit__WindowMinutes=1
      
      # CORS
      - CORS__AllowedOrigins__0=https://*.${DOMAIN:-coreapp-dev.diegolima.dev}
      - CORS__AllowedOrigins__1=http://localhost:3000
      - CORS__AllowedOrigins__2=http://localhost:8080
      
      # Environment
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:8080
      - TZ=America/Sao_Paulo
      
    expose:
      - "8080"
    networks:
      - coreapp_network
      - dokploy-network  # Rede do Dokploy para Traefik
    volumes:
      - app_logs:/app/logs
    labels:
      # Traefik configuration for Dokploy
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      
      # API Router - Desenvolvimento local
      - "traefik.http.routers.coreapp-api.rule=Host(`localhost`)"
      - "traefik.http.routers.coreapp-api.entrypoints=web"
      
      # Service configuration
      - "traefik.http.services.coreapp.loadbalancer.server.port=8080"
      - "traefik.http.services.coreapp.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.coreapp.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.coreapp.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.coreapp.loadbalancer.sticky.cookie.name=coreapp_session"
      
      # Middleware para CORS - Desenvolvimento local
      - "traefik.http.middlewares.coreapp-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.coreapp-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.coreapp-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.coreapp-cors.headers.addvaryheader=true"
      - "traefik.http.routers.coreapp-api.middlewares=coreapp-cors"
      
      # Rate limiting middleware
      - "traefik.http.middlewares.coreapp-ratelimit.ratelimit.burst=10"
      - "traefik.http.middlewares.coreapp-ratelimit.ratelimit.average=100"
      
      # Dokploy metadata
      - "com.dokploy.service=coreapp-coreapi"
      - "com.dokploy.environment=${ENVIRONMENT:-production}"
      - "com.dokploy.project=coreapp-saas"

networks:
  coreapp_network:
    driver: bridge
    name: coreapp_network
  dokploy-network:
    external: true
    name: dokploy-network

volumes:
  postgres_data:
    name: coreapp_postgres_data
  app_logs:
    name: coreapp_app_logs