version: '3.8'

services:
  # PostgreSQL 16 - Database Multi-tenant Brasileiro
  postgres:
    image: postgres:16-alpine
    container_name: farmacia_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: farmacia_saas_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev123456}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d farmacia_saas_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend .NET 9 Multi-tenant
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DOTNET_VERSION=9.0
    container_name: farmacia_backend_dev
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      TZ: America/Sao_Paulo
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=farmacia_saas_dev;User Id=admin;Password=${DB_PASSWORD:-dev123456};"
      JWT__Secret: ${JWT_SECRET:-fake-jwt-secret-brasileiro-super-seguro-farmacia}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/bin:/app/bin
      - ./backend/obj:/app/obj

volumes:
  postgres_data:
    driver: local